// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOY-fQSRP3v-UsoVCKpyAqmMeuLSbiuXc',
    appId: '1:230600071508:web:3e0cb96717e9a50ea710c1',
    messagingSenderId: '230600071508',
    projectId: 'chat-app-b48a8',
    authDomain: 'chat-app-b48a8.firebaseapp.com',
    storageBucket: 'chat-app-b48a8.appspot.com',
    measurementId: 'G-LPYG4WPYW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWQrs81NoJFJZx7G4LNm2XWWI01ZvyqWo',
    appId: '1:230600071508:android:b70caedeaf0e58f8a710c1',
    messagingSenderId: '230600071508',
    projectId: 'chat-app-b48a8',
    storageBucket: 'chat-app-b48a8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbTUQfy1PYiwrRTbGcLX_vwM9fCoKiICM',
    appId: '1:230600071508:ios:d6e75ac9c6a1baa8a710c1',
    messagingSenderId: '230600071508',
    projectId: 'chat-app-b48a8',
    storageBucket: 'chat-app-b48a8.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
